version: '3'
services:
  morphocluster:
    build:
      context: .
      dockerfile: docker/morphocluster/Dockerfile
    ports:
      - "8000:8000"
      # Expose port 22 for external SSH access:
      #- "8022:22"
    depends_on:
      - postgres
    volumes:
      - morphocluster-data:/data
      - ${PWD}/docker/morphocluster/authorized_keys:/authorized_keys:ro
  postgres:
    build: docker/postgresql
    environment:
      POSTGRES_USER: morphocluster
      POSTGRES_PASSWORD: morphocluster
      POSTGRES_DB: morphocluster
    ports:
      ## Expose Port 5432 for direct access of the database.
      ## Remove in production!
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis-rq:
    image: "redis:5-alpine"
    ports:
      - "6379"
  redis-lru:
    build: docker/redis-lru
    ports:
      - "6379"

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      # Location on host filesystem for PostgreSQL data
      device: /data/morphocluster/data
  morphocluster-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      # Location on host filesystem for application data
      device: /data/morphocluster/data
